[build]
  publish = "."
  functions = "api"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@octokit/auth-app"] # Optional: ensures this specific module is handled correctly

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/*"
  status = 200