name = "github-submit"
pages_build_output_dir = "."
compatibility_date = "2026-01-01"
compatibility_flags = [ "nodejs_compat" ]

[vars]
# You'll set your IDs and GH keys via the Cloudflare Dashboard 
# or 'wrangler secret put'